### ISSUE TITLE
Unable to Join Estimating Session

### ISSUE THREAD

**Issue by jtrout** [cschleiden/azure-boards-estimate#129]
Users are unable to enter any estimating session. When one attempts to open on, they receive a persistent "Connecting to server..." spinner. The browser console reports a number of errors, seemingly related to CORS blocking resources:

````
Access to XMLHttpRequest at 'https://estimate-backend.azurewebsites.net//estimate/negotiate?sessionId=3fqwf&tfId=1e59d5ba-d73a-6c63-a81e-b417a1838bb6' from origin 'https://ms-devlabs.gallerycdn.vsassets.io' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.
Utils.js:347 Warning: Error from HTTP request. 0: 
Utils.js:343 Error: Failed to complete negotiation with the server: Error
Utils.js:343 Error: Failed to start the connection: Error
signalr.ts:80 Error
utils.js:262 uncaught at jr at jr 
 at p 
 at Sr 
 at hr 
 Error: Cannot send data if the connection is not in the 'Connected' State.
    at e.send (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:326965)
    at e.send (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:308835)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/main.cccf3539.chunk.js:1:65033
    at x (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:427102)
    at Generator._invoke (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:426890)
    at Generator.e.<computed> [as next] (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:427281)
    at r (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:16673)
    at s (https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:16875)
    at https://ms-devlabs.gallerycdn.vsassets.io/extensions/ms-devlabs/estimate/2.2.3/1567200928692/build/static/js/1.c2732b68.chunk.js:1:16934
    at new Promise (<anonymous>)

**Comment by joetcochran** [comment]
We are having a similar issue - like the app service is down?

**Comment by Aldebaran91** [comment]
Not working on Azure DevOps Server.

**Comment by Aldebaran91** [comment]
@cschleiden please add the missing CORS in your typescript!

https://brianflove.com/2017-03-22/express-cors-typescript/

**Comment by john-gWlayne** [comment]
We are facing the issues too.

**Comment by Sebbl22** [comment]
Same issue here

**Comment by jlundstocholm** [comment]
We are having the same issue with our customers running Azure DevOps Services. However - i would imagine that if the root cause was missing CORS-headers, then no-one would be able to access the extension. For our customers it is a flaky issue that happens every now and then and after "randomly clicking" in other parts of Azure DevOps they are able to use the extension.

**Comment by shirinemasood** [comment]
We are having this issue with some team members. If they click on the "Estmate" menu option from Azure Boards, they are taken to the main landing page but cannot see any sessions (past or newly created). If we give them the direct link to a session they get this error:
<Error>

<Code>ResourceNotFound</Code>
<Message>The specified resource does not exist. RequestId:b38967ad-701e-0068-07d5-741956000000 Time:2020-08-17T20:33:36.5845236Z</Message>

</Error>

In one instance, the team member was able to get to the session later, in some instances not.
